name: Lint Code Base

on: [push, pull_request]

jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '14' # Specify the node version
    - name: Install Dependencies
      run: npm ci
    - name: Run ESLint
      run: npx eslint *.js
